import { randomUUID } from 'node:crypto';
import { SPAWN, MOB_SPAWNS, PROPS, move } from '../shared/world.js';
export const ABILITIES = { attack: { cooldown: .55, range: 2.8, damage: 24 }, nova: { cooldown: 5, range: 5.5, damage: 38 }, heal: { cooldown: 9 } };
export class World {
  constructor() { this.config={moveSpeed:6,enemySpeed:2.1,enemyDamage:8}; this.players=new Map(); this.time=0; this.events=[]; this.mobs=MOB_SPAWNS.map(([x,z],i)=>({id:`mob-${i}`,x,z,homeX:x,homeZ:z,hp:60,respawn:0,hitAt:0})); }
  join(name='Wanderer') { const p={id:randomUUID(), name:String(name).slice(0,20),...SPAWN,hp:100,xp:0,gold:0,kills:0,quest:false,level:1,angle:0, input:{x:0,z:0}, cooldowns:{attack:0,nova:0,heal:0}}; this.players.set(p.id,p); return p; }
  input(id,data) { const p=this.players.get(id); if(!p) return; const x=Number(data.x),z=Number(data.z); if(!Number.isFinite(x)||!Number.isFinite(z)) return; const length=Math.max(1,Math.hypot(x,z)); p.input={x:x/length,z:z/length}; p.inputAt=this.time; }
  ability(id,key) { const p=this.players.get(id),a=ABILITIES[key]; if(!p||!a||p.cooldowns[key]>this.time||p.hp<=0) return false; p.cooldowns[key]=this.time+a.cooldown; this.events.push({type:'ability',id,key,x:p.x,z:p.z}); if(key==='heal') { p.hp=Math.min(100,p.hp+40); return true; } for(const m of this.mobs) { if(m.hp<=0||Math.hypot(m.x-p.x,m.z-p.z)>a.range) continue; m.hp=Math.max(0,m.hp-a.damage); this.events.push({type:'damage',x:m.x,z:m.z,amount:a.damage}); if(m.hp===0) { m.respawn=this.time+15; p.kills++; p.xp+=20; p.gold+=8; if(p.kills>=5&&!p.quest) { p.quest=true;p.xp+=150;p.gold+=50;this.events.push({type:'quest',id}); } p.level=1+Math.floor(p.xp/100); } } return true; }
  tick(dt) { this.time+=dt; const camps=PROPS.filter(p=>p.model==='campfire');for(const p of this.players.values()) { if(this.time-(p.inputAt??0)>.35) p.input={x:0,z:0}; const {x,z}=p.input; move(p,x*this.config.moveSpeed*dt,z*this.config.moveSpeed*dt); if(x||z) p.angle=Math.atan2(x,z); if(p.hp<=0) {p.hp=100;p.x=SPAWN.x;p.z=SPAWN.z;this.events.push({type:'respawn',id:p.id});} if(camps.some(c=>Math.hypot(p.x-c.x,p.z-c.z)<4*c.scale)) p.hp=Math.min(100,p.hp+dt*5); }
    for(const m of this.mobs) { if(m.hp<=0) { if(this.time>=m.respawn) {m.hp=60;m.x=m.homeX;m.z=m.homeZ;} continue; } let target=null,nearest=9; for(const p of this.players.values()) {const d=Math.hypot(m.x-p.x,m.z-p.z);if(d<nearest){target=p;nearest=d;}} const tx=target?.x??m.homeX,tz=target?.z??m.homeZ,d=Math.hypot(tx-m.x,tz-m.z); if(d>0&&(target||d>1.25)) m.angle=Math.atan2(tx-m.x,tz-m.z); if(d>1.25) move(m,(tx-m.x)/d*this.config.enemySpeed*dt,(tz-m.z)/d*this.config.enemySpeed*dt); if(target&&d<1.6&&this.time>=m.hitAt) {target.hp=Math.max(0,target.hp-this.config.enemyDamage);m.hitAt=this.time+1.1;this.events.push({type:'hurt',id:target.id,x:target.x,z:target.z,amount:this.config.enemyDamage});} }
  }
  snapshot() { return {type:'state',time:this.time,players:[...this.players.values()].map(({input,inputAt,...p})=>p),mobs:this.mobs.map(({homeX,homeZ,...m})=>m),events:this.events.splice(0)}; }
}
