import './style.css';
import * as T from 'three';
import { createEnvironment } from './environment.js';
import { createEditor } from './editor.js';
import { createPerformanceRecorder } from './performance.js';
import { LAKE, TREES, PROPS, move, SPAWN, random, onPath } from '../shared/world.js';

const $=s=>document.querySelector(s);
let toastTimer;function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
if(import.meta.hot)import.meta.hot.on('world-placements-error',data=>toast(`Invalid placements · keeping current scene: ${data.message}`));
const scene=new T.Scene();const camera=new T.OrthographicCamera(-16,16,10,-10,.1,150);
const renderer=new T.WebGLRenderer({canvas:$('#game'),antialias:true,powerPreference:'high-performance'});renderer.toneMapping=T.ACESFilmicToneMapping;renderer.shadowMap.type=T.PCFSoftShadowMap;
const gl=renderer.getContext(),gpuInfo=gl.getExtension('WEBGL_debug_renderer_info');const gpu=gpuInfo?gl.getParameter(gpuInfo.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER);
const target=new T.Vector3(SPAWN.x,0,SPAWN.z),raycaster=new T.Raycaster(),plane=new T.Plane(new T.Vector3(0,1,0),0);
let editor,environment,settings,recorder,localId=null,state={time:0,players:[],mobs:[]},connected=false,ws,reconnectTimer;
const keys=new Set(),entities=new Map(),effects=[],floaters=[];let clickTarget=null,lastInput=0,clock=0,frames=0,fps=60,lastFps=0;
const cursor=new T.Mesh(new T.RingGeometry(.33,.39,32),new T.MeshBasicMaterial({color:'#ecd494',side:T.DoubleSide,transparent:true,opacity:.8}));cursor.rotation.x=-Math.PI/2;cursor.visible=false;scene.add(cursor);
const selfRing=new T.Mesh(new T.RingGeometry(.53,.60,32),new T.MeshBasicMaterial({color:'#d5d89e',side:T.DoubleSide,transparent:true,opacity:.65}));selfRing.rotation.x=-Math.PI/2;scene.add(selfRing);
function resize(){const aspect=innerWidth/innerHeight;camera.left=-11*aspect;camera.right=11*aspect;camera.top=11;camera.bottom=-11;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);}
addEventListener('resize',resize);
function send(data){if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify(data));}
function logChat(name,text){const p=document.createElement('p');const b=document.createElement('span');b.style.color='#d1c38d';b.textContent=name+': ';p.append(b,document.createTextNode(text));$('#messages').append(p);while($('#messages').children.length>40)$('#messages').firstChild.remove();$('#messages').scrollTop=$('#messages').scrollHeight;}
function connect(){ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);ws.addEventListener('open',()=>{connected=true;$('#network').textContent='World connected';$('#network').classList.add('connected');});ws.addEventListener('close',()=>{connected=false;localId=null;keys.clear();clickTarget=null;$('#network').textContent='Reconnecting…';$('#network').classList.remove('connected');clearTimeout(reconnectTimer);reconnectTimer=setTimeout(connect,1500);});ws.addEventListener('message',event=>{const data=JSON.parse(event.data);if(data.type==='welcome'){localId=data.id;target.set(SPAWN.x,0,SPAWN.z);}if(data.type==='chat')logChat(data.name,data.text);if(data.type==='state'){state=data;syncEntities();for(const e of data.events)handleEvent(e);}});}
function makeEntity(data,mob){const group=new T.Group();const model=environment.models[mob?'mossling':'wanderer'].clone();model.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;}});group.add(model);group.position.set(data.x,0,data.z);scene.add(group);let health=null;if(mob){health=new T.Mesh(new T.PlaneGeometry(.9,.085),new T.MeshBasicMaterial({color:'#c5452b',depthTest:false}));health.position.y=2.15;group.add(health);}const record={group,model,health,data,mob};entities.set(data.id,record);return record;}
function syncEntities(){const ids=new Set();for(const [list,mob] of [[state.players,false],[state.mobs,true]])for(const data of list){ids.add(data.id);let e=entities.get(data.id);if(!e)e=makeEntity(data,mob);e.data=data;e.group.visible=data.hp>0;if(data.id===localId&&Math.hypot(e.group.position.x-data.x,e.group.position.z-data.z)>3)e.group.position.set(data.x,0,data.z);}for(const [id,e] of entities)if(!ids.has(id)){scene.remove(e.group);if(e.health){e.health.geometry.dispose();e.health.material.dispose();}entities.delete(id);}$('#online').textContent=`${state.players.length} adventurer${state.players.length===1?'':'s'}`;}
function effect(x,z,color,range){const mesh=new T.Mesh(new T.RingGeometry(.7,.85,48),new T.MeshBasicMaterial({color,transparent:true,opacity:.9,side:T.DoubleSide,depthWrite:false}));mesh.position.set(x,.07,z);mesh.rotation.x=-Math.PI/2;scene.add(mesh);effects.push({mesh,age:0,range});}
function floating(x,z,amount,hurt=false){const el=document.createElement('div');el.className=`damage${hurt?' hurt':''}`;el.textContent=String(amount);document.body.append(el);floaters.push({el,pos:new T.Vector3(x,1.6,z),age:0});}
function handleEvent(e){if(e.type==='ability')effect(e.x,e.z,e.key==='heal'?'#a5dc96':e.key==='nova'?'#81d9c3':'#e6cd8b',e.key==='nova'?5.5:e.key==='heal'?2:2.8);if(e.type==='damage')floating(e.x,e.z,e.amount);if(e.type==='hurt'&&e.id===localId)floating(e.x,e.z,e.amount,true);if(e.type==='quest'&&e.id===localId)toast('Quest complete · +150 experience · +50 gold');if(e.type==='respawn'&&e.id===localId)toast('The wardstone returned you to camp');}
function ability(key){if(!connected)return;send({type:'ability',key});}
addEventListener('keydown',e=>{const typing=['INPUT','SELECT','TEXTAREA'].includes(document.activeElement.tagName);if(e.code==='F3'){e.preventDefault();$('#debug').hidden=!$('#debug').hidden;return;}if(typing){if(e.code==='Escape')document.activeElement.blur();return;}if(e.code==='Enter'){e.preventDefault();$('#chat-input').focus();return;}if(e.code==='Escape'){keys.clear();clickTarget=null;return;}if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowLeft','ArrowDown','ArrowRight','Space','KeyQ','KeyE'].includes(e.code))e.preventDefault();keys.add(e.code);if(!e.repeat){if(e.code==='Space')ability('attack');if(e.code==='KeyQ')ability('nova');if(e.code==='KeyE')ability('heal');}});
addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>{keys.clear();clickTarget=null;send({type:'input',x:0,z:0});});
$('#chat-input').addEventListener('focus',()=>{keys.clear();clickTarget=null;send({type:'input',x:0,z:0});});
$('#chat-form').addEventListener('submit',e=>{e.preventDefault();const input=$('#chat-input');if(input.value.trim()){send({type:'chat',text:input.value});input.value='';}input.blur();});
document.querySelectorAll('[data-ability]').forEach(button=>button.addEventListener('click',()=>ability(button.dataset.ability)));
$('#quality').addEventListener('change',e=>{renderer.setPixelRatio(Math.min(devicePixelRatio,Number(e.target.value)));resize();});
$('#game').addEventListener('pointerdown',e=>{if(e.button!==0)return;document.activeElement?.blur();raycaster.setFromCamera(new T.Vector2(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1),camera);const point=raycaster.ray.intersectPlane(plane,new T.Vector3());if(point){clickTarget={x:point.x,z:point.z};cursor.position.set(point.x,.04,point.z);cursor.visible=true;}});
function inputDirection(){let right=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0),forward=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0);let x=(right+forward)*Math.SQRT1_2,z=(forward-right)*Math.SQRT1_2;const self=entities.get(localId);if(x||z){clickTarget=null;cursor.visible=false;}else if(clickTarget&&self){x=clickTarget.x-self.group.position.x;z=clickTarget.z-self.group.position.z;if(Math.hypot(x,z)<.3){clickTarget=null;cursor.visible=false;x=z=0;}}const len=Math.hypot(x,z);if(len>0){x/=len;z/=len;}return {x,z};}
const map=$('#minimap'),ctx=map.getContext('2d');
const mapBase=document.createElement('canvas');mapBase.width=map.width;mapBase.height=map.height;
const mapPaint=mapBase.getContext('2d'),mapRandom=random(42),mapScale=map.width/88;
for(let x=0;x<map.width;x+=2)for(let y=0;y<map.height;y+=2){const shade=Math.floor(mapRandom()*12),road=onPath(x/mapScale-44,y/mapScale-44);mapPaint.fillStyle=road?`rgb(${100+shade},${85+shade},${53+shade})`:`rgb(${48+shade},${59+shade},${32+shade})`;mapPaint.fillRect(x,y,2,2);}
mapPaint.fillStyle='#263a27';for(const t of TREES){mapPaint.beginPath();mapPaint.arc((t.x+44)*mapScale,(t.z+44)*mapScale,2.4,0,Math.PI*2);mapPaint.fill();}
mapPaint.fillStyle='#365d68';mapPaint.strokeStyle='#81938a';mapPaint.lineWidth=1;mapPaint.beginPath();mapPaint.arc((LAKE.x+44)*mapScale,(LAKE.z+44)*mapScale,LAKE.radius*mapScale,0,Math.PI*2);mapPaint.fill();mapPaint.stroke();
function minimap(){ctx.drawImage(mapBase,0,0);for(const m of state.mobs)if(m.hp>0){ctx.fillStyle='#d16b4d';ctx.beginPath();ctx.arc((m.x+44)*mapScale,(m.z+44)*mapScale,2,0,Math.PI*2);ctx.fill();}for(const p of state.players){ctx.save();ctx.translate((p.x+44)*mapScale,(p.z+44)*mapScale);ctx.rotate(-p.angle);ctx.fillStyle=p.id===localId?'#eee4ca':'#99dad2';ctx.strokeStyle='#17201d';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(0,5);ctx.lineTo(-4,-4);ctx.lineTo(0,-2);ctx.lineTo(4,-4);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();}}
function updateUI(){const p=state.players.find(p=>p.id===localId);if(!p)return;$('#hp-bar').style.width=p.hp+'%';$('#hp-label').textContent=`${Math.round(p.hp)} / 100`;$('#level').textContent=String(p.level);$('#xp-bar').style.width=p.xp%100+'%';$('#gold').textContent=p.gold;$('#quest-progress').textContent=p.quest?'Completed':`${Math.min(p.kills,5)} / 5 creatures`;$('#coordinates').textContent=`${p.x.toFixed(0)}, ${p.z.toFixed(0)}`;for(const [key,seconds] of [['attack',.55],['nova',5],['heal',9]]){const remaining=Math.max(0,p.cooldowns[key]-state.time);const button=$(`[data-ability="${key}"]`);button.querySelector('i').style.height=`${remaining/seconds*100}%`;button.setAttribute('aria-label',`${key}${remaining?` cooldown ${remaining.toFixed(1)} seconds`:''}`);}}
let last=performance.now();function frame(now){const frameStarted=performance.now();requestAnimationFrame(frame);const dt=Math.min(.05,(now-last)/1000);last=now;clock+=dt;frames++;if(now-lastFps>1000){fps=Math.round(frames*1000/(now-lastFps));frames=0;lastFps=now;}
  const direction=inputDirection(),self=entities.get(localId);if(connected&&now-lastInput>50){send({type:'input',...direction});lastInput=now;}
  // Blender -Y exports as +Z, matching the server's atan2(x, z) heading.
  for(const [id,e] of entities){const p=e.group.position,d=e.data;if(id===localId){const predicted={x:p.x,z:p.z};move(predicted,direction.x*settings.gameplay.moveSpeed*dt,direction.z*settings.gameplay.moveSpeed*dt);p.x=predicted.x;p.z=predicted.z;if(!direction.x&&!direction.z){p.x=T.MathUtils.lerp(p.x,d.x,Math.min(1,dt*10));p.z=T.MathUtils.lerp(p.z,d.z,Math.min(1,dt*10));}e.group.rotation.y=direction.x||direction.z?Math.atan2(direction.x,direction.z):d.angle;}else{p.x=T.MathUtils.lerp(p.x,d.x,Math.min(1,dt*12));p.z=T.MathUtils.lerp(p.z,d.z,Math.min(1,dt*12));e.group.rotation.y=d.angle??0;}e.model.position.y=e.mob?Math.sin(clock*3+d.x)*.035:(id===localId&&(direction.x||direction.z)?Math.abs(Math.sin(clock*12))*.065:0);if(e.health){e.health.scale.x=d.hp/60;e.health.quaternion.copy(camera.quaternion).premultiply(e.group.quaternion.clone().invert());}}
  if(self){target.lerp(new T.Vector3(self.group.position.x,0,self.group.position.z),1-Math.exp(-dt*9));selfRing.position.set(self.group.position.x,.035,self.group.position.z);}
  const elevation=settings.camera.angle*Math.PI/180,distance=settings.camera.distance;camera.position.set(target.x+distance*Math.cos(elevation)*Math.SQRT1_2,distance*Math.sin(elevation),target.z+distance*Math.cos(elevation)*Math.SQRT1_2);camera.lookAt(target);camera.zoom=settings.camera.zoom*23/distance;camera.updateProjectionMatrix();environment.update(clock,target);
  for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.age+=dt;e.mesh.scale.setScalar(.5+e.age*e.range*2);e.mesh.material.opacity=Math.max(0,1-e.age*2);if(e.age>.5){scene.remove(e.mesh);e.mesh.geometry.dispose();e.mesh.material.dispose();effects.splice(i,1);}}
  for(let i=floaters.length-1;i>=0;i--){const f=floaters[i];f.age+=dt;const p=f.pos.clone();p.y+=f.age*1.8;p.project(camera);f.el.style.left=`${(p.x*.5+.5)*innerWidth}px`;f.el.style.top=`${(-p.y*.5+.5)*innerHeight}px`;f.el.style.opacity=1-f.age;if(f.age>1){f.el.remove();floaters.splice(i,1);}}
  const renderStarted=performance.now();renderer.render(scene,camera);const renderSubmitMs=performance.now()-renderStarted;
  if(frames%8===0){updateUI();minimap();$('#metrics').textContent=`${fps} FPS\n${renderer.info.render.calls} draw calls\n${renderer.info.render.triangles.toLocaleString()} triangles\n${state.players.length} players · ${state.mobs.length} mobs\nGrass: ${settings.grass.density}\nServer: 20 Hz · network: 10 Hz\n${recorder?.status??''}`;}
  recorder?.frame(now,performance.now()-frameStarted,renderSubmitMs);
}
// Read-only, stable observability hook for AI playtests. Actions use actual UI.
Object.defineProperty(window,'__game',{value:{get ready(){return Boolean(environment&&settings&&localId);},get state(){return structuredClone(state);},get playerId(){return localId;},get config(){return structuredClone(settings);},get placements(){return structuredClone(PROPS);},get performanceLog(){return {sessionId:recorder?.sessionId,status:recorder?.status,lastSample:recorder?.lastSample};},get metrics(){return {fps,drawCalls:renderer.info.render.calls,triangles:renderer.info.render.triangles,gpu};},project(x,z){const p=new T.Vector3(x,0,z).project(camera);return {x:(p.x*.5+.5)*innerWidth,y:(-p.y*.5+.5)*innerHeight};}},writable:false});
Object.defineProperty(window.__game,'entities',{get(){return [...entities].map(([id,e])=>({id,mob:e.mob,x:e.group.position.x,z:e.group.position.z,angle:e.group.rotation.y}));}});
try{environment=await createEnvironment(scene,renderer);editor=await createEditor(config=>{settings=config;environment.apply(config);resize();},toast);recorder=createPerformanceRecorder(renderer,gpu,()=>({players:state.players.length,mobs:state.mobs.filter(m=>m.hp>0).length,grassDensity:settings.grass.density,shadows:settings.performance.shadows,cameraDistance:settings.camera.distance,cameraAngle:settings.camera.angle,cameraZoom:settings.camera.zoom,exposure:settings.lighting.exposure}));resize();connect();$('#loading').remove();requestAnimationFrame(frame);}catch(error){console.error(error);$('#loading').textContent=`Unable to enter the vale: ${error.message}. Run mise run assets and mise run dev.`;}
