import './map-editor.css';
import { MATERIALS,MAP_MODELS,PALETTES,compileMap,inside,segmentDistance,validateMap } from '../shared/map.js';
const $=s=>document.querySelector(s),canvas=$('#atlas'),ctx=canvas.getContext('2d');
let map,revision,compiled,selected=null,vertex=0,draft=[],history=[],future=[],drag=null,dirty=false,view={x:0,z:0,zoom:1};
const status=text=>$('#status').textContent=text;
for(const [value] of Object.entries(MATERIALS))$('#material').add(new Option(value,value));for(const n of MAP_MODELS)$('#model').add(new Option(n,n));
function records(){return [...map.regions,...map.paths,...map.props];}function selection(){return records().find(r=>r.id===selected);}
function checkpoint(){history.push(JSON.stringify(map));if(history.length>60)history.shift();future=[];dirty=true;}
function rebuild(){compiled=compileMap(map);$('#title').textContent=map.name;$('#summary').textContent=`${map.size} × ${map.size} · ${map.regions.length} regions · ${compiled.props.length} props${dirty?' · Unsaved':''}`;draw();}
function panel(){const select=$('#selection');select.replaceChildren(new Option('No selection',''));for(const r of records())select.add(new Option(`${r.id} · ${r.material??r.model}`,r.id));select.value=selected??'';const r=selection();if(r?.material)$('#material').value=r.material;if(r?.width)$('#width').value=r.width;if(r?.model){$('#model').value=r.model;$('#scale').value=r.scale;$('#rotation').value=r.rotation*180/Math.PI;}
  $('#vertices').replaceChildren();if(r?.points)r.points.forEach((p,i)=>{const label=document.createElement('label');label.append(document.createTextNode(`Vertex ${i+1}`));for(let k=0;k<2;k++){const input=document.createElement('input');input.type='number';input.step='.25';input.value=p[k];input.setAttribute('aria-label',`Vertex ${i+1} ${k?'Z':'X'}`);input.onchange=()=>{const next=Math.max(-map.size/2,Math.min(map.size/2,Number(input.value)));if(next===p[k])return;checkpoint();p[k]=next;vertex=i;rebuild();};label.append(input);}$('#vertices').append(label);});
}
function screen(x,z){return {x:(x-view.x)*view.zoom+canvas.width/2,y:(z-view.z)*view.zoom+canvas.height/2};}function world(e){const b=canvas.getBoundingClientRect();return {x:(e.clientX-b.left-canvas.width/2)/view.zoom+view.x,z:(e.clientY-b.top-canvas.height/2)/view.zoom+view.z};}
function shape(points,close=true){ctx.beginPath();points.forEach(([x,z],i)=>{const p=screen(x,z);i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y);});if(close)ctx.closePath();}
function draw(){if(!map)return;ctx.fillStyle='#152125';ctx.fillRect(0,0,canvas.width,canvas.height);const a=screen(-map.size/2,-map.size/2),size=map.size*view.zoom;ctx.fillStyle=MATERIALS[map.base];ctx.fillRect(a.x,a.y,size,size);
  for(const r of map.regions){shape(r.points);ctx.fillStyle=MATERIALS[r.material];ctx.fill();}for(const p of map.paths){shape(p.points,false);ctx.strokeStyle=MATERIALS[p.material];ctx.lineWidth=p.width*view.zoom;ctx.lineJoin=ctx.lineCap='round';ctx.stroke();}
  ctx.strokeStyle='#ffffff14';ctx.lineWidth=1;for(let x=-map.size/2;x<=map.size/2;x+=64){const p=screen(x,-map.size/2),q=screen(x,map.size/2);ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();const s=screen(-map.size/2,x),t=screen(map.size/2,x);ctx.beginPath();ctx.moveTo(s.x,s.y);ctx.lineTo(t.x,t.y);ctx.stroke();}
  for(const p of compiled.props){const s=screen(p.x,p.z);ctx.fillStyle=p.model.includes('house')?'#ebbd83':p.model==='ruin'?'#b1aca2':p.model==='snow-pine'?'#f1f5f2':'#293e30';ctx.beginPath();ctx.arc(s.x,s.y,Math.max(1.2,(p.model.includes('house')?3.5:1.5)*p.scale*view.zoom),0,Math.PI*2);ctx.fill();}
  const origin=screen(-44,-44);ctx.strokeStyle='#ffe6a5';ctx.lineWidth=1;ctx.strokeRect(origin.x,origin.y,88*view.zoom,88*view.zoom);ctx.fillStyle='#ffe6a5';ctx.font='11px system-ui';ctx.fillText('STARTER VALE',origin.x+4,origin.y+14);
  const r=selection();if(r?.points){shape(r.points,!r.width);ctx.strokeStyle='#ffe6a5';ctx.lineWidth=2;ctx.stroke();r.points.forEach(([x,z],i)=>{const p=screen(x,z);ctx.fillStyle=i===vertex?'#fff':'#efb971';ctx.fillRect(p.x-4,p.y-4,8,8);});}else if(r){const p=screen(r.x,r.z);ctx.strokeStyle='#ffe6a5';ctx.lineWidth=2;ctx.strokeRect(p.x-8,p.y-8,16,16);}
  if(draft.length){shape(draft,false);ctx.strokeStyle='#ffe6a5';ctx.lineWidth=2;ctx.stroke();for(const [x,z] of draft){const p=screen(x,z);ctx.fillStyle='#fff';ctx.fillRect(p.x-3,p.y-3,6,6);}}
}
function fit(){view={x:0,z:0,zoom:Math.min(canvas.width,canvas.height)/(map.size*1.1)};draw();}
function resize(){const b=canvas.getBoundingClientRect();canvas.width=b.width;canvas.height=b.height;draw();}new ResizeObserver(resize).observe(canvas);
async function load(){if(dirty&&!confirm('Discard unsaved map edits?'))return;const response=await fetch('/__map');if(!response.ok)throw new Error('Map editor requires mise run dev');const data=await response.json();map=data.document;revision=data.revision;history=[];future=[];dirty=false;selected=null;rebuild();panel();fit();status('Loaded world/map.json');}
const id=prefix=>`${prefix}-${crypto.randomUUID().slice(0,8)}`;
function finish(){const tool=$('#tool').value;if(draft.length<(tool==='path'?2:3)){status('Add more points before finishing.');return;}checkpoint();const r={id:id(tool),material:$('#material').value,points:draft.map(p=>p.slice()),...(tool==='path'?{width:Number($('#width').value)}:{})};(tool==='path'?map.paths:map.regions).push(r);selected=r.id;draft=[];$('#tool').value='select';rebuild();panel();status('Shape added. Drag vertices for fine control.');}
canvas.oncontextmenu=e=>e.preventDefault();canvas.onpointerdown=e=>{const p=world(e);canvas.setPointerCapture(e.pointerId);if(e.button===1||e.button===2){drag={kind:'pan',sx:e.clientX,sy:e.clientY,x:view.x,z:view.z};return;}
  const tool=$('#tool').value;if(tool==='region'||tool==='path'){draft.push([Math.max(-map.size/2,Math.min(map.size/2,p.x)),Math.max(-map.size/2,Math.min(map.size/2,p.z))]);draw();return;}
  if(tool==='prop'){checkpoint();const prop={id:id('prop'),model:$('#model').value,x:p.x,z:p.z,rotation:Number($('#rotation').value)*Math.PI/180,scale:Number($('#scale').value)};map.props.push(prop);try{rebuild();selected=prop.id;panel();}catch(error){map.props.pop();rebuild();status(error.message);}return;}
  const r=selection();const i=r?.points?.findIndex(([x,z])=>Math.hypot(x-p.x,z-p.z)*view.zoom<12);if(i>=0){checkpoint();vertex=i;drag={kind:'vertex',r,i};draw();return;}
  const prop=[...map.props].reverse().find(r=>Math.hypot(p.x-r.x,p.z-r.z)*view.zoom<12);if(prop){selected=prop.id;checkpoint();drag={kind:'prop',r:prop};panel();draw();return;}
  selected=[...map.paths].reverse().find(r=>r.points.slice(1).some((b,i)=>segmentDistance(p.x,p.z,r.points[i],b)<Math.max(r.width/2,6/view.zoom)))?.id??[...map.regions].reverse().find(r=>inside(p.x,p.z,r.points))?.id??null;vertex=0;panel();draw();};
canvas.onpointermove=e=>{const p=world(e);$('#position').textContent=`X ${p.x.toFixed(1)} · Z ${p.z.toFixed(1)}`;if(!drag)return;if(drag.kind==='pan'){view.x=drag.x-(e.clientX-drag.sx)/view.zoom;view.z=drag.z-(e.clientY-drag.sy)/view.zoom;}else{const x=Math.max(-map.size/2+.01,Math.min(map.size/2-.01,p.x)),z=Math.max(-map.size/2+.01,Math.min(map.size/2-.01,p.z));if(drag.kind==='vertex')drag.r.points[drag.i]=[x,z];else{drag.r.x=x;drag.r.z=z;}}draw();};
canvas.onpointerup=()=>{if(drag&&drag.kind!=='pan'){try{rebuild();}catch(e){map=JSON.parse(history.pop());rebuild();status(e.message);}panel();}drag=null;};canvas.onpointercancel=()=>{drag=null;};
canvas.onwheel=e=>{e.preventDefault();const before=world(e);view.zoom=Math.max(.15,Math.min(12,view.zoom*Math.exp(-e.deltaY*.001)));const after=world(e);view.x+=before.x-after.x;view.z+=before.z-after.z;draw();};
$('#selection').onchange=e=>{selected=e.target.value;vertex=0;panel();draw();};$('#finish').onclick=finish;$('#cancel').onclick=()=>{draft=[];draw();};$('#fit').onclick=fit;$('#reload').onclick=()=>load().catch(e=>status(e.message));
$('#tool').onchange=()=>{draft=[];if($('#tool').value!=='select')selected=null;if($('#tool').value==='path')$('#material').value='path';panel();draw();};
$('#delete').onclick=()=>{if(!selection())return;checkpoint();for(const key of ['regions','paths','props'])map[key]=map[key].filter(r=>r.id!==selected);map.scatter=map.scatter.filter(r=>r.region!==selected);selected=null;rebuild();panel();};
$('#insert').onclick=()=>{const r=selection();if(!r?.points)return;checkpoint();const a=r.points[vertex],b=r.points[(vertex+1)%r.points.length];r.points.splice(vertex+1,0,[(a[0]+b[0])/2,(a[1]+b[1])/2]);vertex++;rebuild();panel();};
$('#remove-vertex').onclick=()=>{const r=selection();if(!r?.points||r.points.length<=(r.width?2:3))return;checkpoint();r.points.splice(vertex,1);vertex=0;rebuild();panel();};
for(const key of ['material','width','model','scale','rotation'])$('#'+key).onchange=()=>{const r=selection();if(!r)return;checkpoint();if(key==='rotation'&&r.model)r.rotation=Number($('#rotation').value)*Math.PI/180;else if(key in r)r[key]=['width','scale'].includes(key)?Number($('#'+key).value):$('#'+key).value;try{rebuild();}catch(e){map=JSON.parse(history.pop());rebuild();status(e.message);}panel();};
$('#scatter').onclick=()=>{const r=map.regions.find(r=>r.id===selected);if(!r||!PALETTES[r.material])return status('Select a grass, snow, sand or rock region.');checkpoint();map.scatter=map.scatter.filter(s=>s.region!==r.id);map.scatter.push({id:id('scatter'),region:r.id,seed:Number($('#seed').value),density:Number($('#density').value),spacing:Number($('#spacing').value),models:$('#palette').value==='auto'?PALETTES[r.material]:$('#palette').value.split(',')});try{rebuild();status('Placement generated. Change seed or density to refine.');}catch(e){map=JSON.parse(history.pop());rebuild();status(e.message);}};
for(const key of ['undo','redo'])$('#'+key).onclick=()=>{const from=key==='undo'?history:future,to=key==='undo'?future:history;if(!from.length)return;to.push(JSON.stringify(map));map=JSON.parse(from.pop());dirty=true;rebuild();panel();};
$('#save').onclick=async()=>{const button=$('#save');button.disabled=true;try{validateMap(map);const response=await fetch('/__map',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({document:map,revision})}),data=await response.json();if(!response.ok)throw new Error(data.error);revision=data.revision;dirty=false;rebuild();status('Saved world/map.json. Game and server reload the map.');}catch(e){status(e.message);}finally{button.disabled=false;}};
$('#export').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(map,null,2)],{type:'application/json'}));a.download='map.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$('#import').onchange=async e=>{try{const next=validateMap(JSON.parse(await e.target.files[0].text()));compileMap(next);checkpoint();map=next;selected=null;rebuild();panel();fit();}catch(error){status(error.message);}};
addEventListener('keydown',e=>{if(['INPUT','SELECT'].includes(document.activeElement.tagName))return;if(e.key==='Enter'&&draft.length)finish();if(e.key==='Escape'){draft=[];drag=null;draw();}});addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
await load().catch(e=>status(e.message));
